#!/usr/bin/env bash
set -euo pipefail

KICAD_CLI="/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCH="$PROJECT_DIR/PCB/hairtag/hairtag.kicad_sch"
PCB="$PROJECT_DIR/PCB/hairtag/hairtag.kicad_pcb"
OUT_DIR="$PROJECT_DIR/doc"

mkdir -p "$OUT_DIR"

echo "Exporting schematic SVG..."
"$KICAD_CLI" sch export svg -o "$OUT_DIR" "$SCH"

if [ -f "$OUT_DIR/hairtag.svg" ]; then
  mv "$OUT_DIR/hairtag.svg" "$OUT_DIR/schematic.svg"
  echo "  -> doc/schematic.svg"
fi

echo "Exporting PCB composite SVG..."
"$KICAD_CLI" pcb export svg \
  --output "$OUT_DIR/pcb.svg" \
  --layers "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts,F.Fab,B.Fab" \
  --page-size-mode 2 \
  --fit-page-to-board \
  --exclude-drawing-sheet \
  "$PCB"

# Add margin (5mm on each side) by expanding the viewBox
# SVG units are mm in KiCad exports
MARGIN=5
VIEWBOX_LINE=$(grep -o 'viewBox="[^"]*"' "$OUT_DIR/pcb.svg")
VX=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\1/')
VY=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\2/')
VW=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\3/')
VH=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\4/')
NEW_VX=$(echo "$VX - $MARGIN" | bc)
NEW_VY=$(echo "$VY - $MARGIN" | bc)
NEW_VW=$(echo "$VW + 2 * $MARGIN" | bc)
NEW_VH=$(echo "$VH + 2 * $MARGIN" | bc)
sed -i '' "s/viewBox=\"[^\"]*\"/viewBox=\"$NEW_VX $NEW_VY $NEW_VW $NEW_VH\"/" "$OUT_DIR/pcb.svg"

# Make copper layers semi-transparent so both sides are visible
sed -i '' 's/fill:#4D7FC4; fill-opacity:1.0000/fill:#4D7FC4; fill-opacity:0.6/g' "$OUT_DIR/pcb.svg"
sed -i '' 's/fill:#C83434; fill-opacity:1.0000/fill:#C83434; fill-opacity:0.6/g' "$OUT_DIR/pcb.svg"

# Add dark background
sed -i '' "/<desc>Image generated by PCBNEW <\/desc>/a\\
<!-- Background rectangle -->\\
<rect x=\"$NEW_VX\" y=\"$NEW_VY\" width=\"$NEW_VW\" height=\"$NEW_VH\" fill=\"#001124\"/>
" "$OUT_DIR/pcb.svg"
echo "  -> doc/pcb.svg"

echo "Rendering PCB 3D top view..."
"$KICAD_CLI" pcb render \
  --side top \
  --quality high \
  --width 2000 \
  --height 2000 \
  -o "$OUT_DIR/pcb_3d_top.png" \
  "$PCB"
echo "  -> doc/pcb_3d_top.png"

echo "Done! Exported to doc/"
