#!/usr/bin/env bash
set -euo pipefail

KICAD_CLI="/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCH="$PROJECT_DIR/PCB/hairtag/hairtag.kicad_sch"
PCB="$PROJECT_DIR/PCB/hairtag/hairtag.kicad_pcb"
OUT_DIR="$PROJECT_DIR/doc"

mkdir -p "$OUT_DIR"

echo "Exporting schematic SVG..."
"$KICAD_CLI" sch export svg -o "$OUT_DIR" "$SCH"

if [ -f "$OUT_DIR/hairtag.svg" ]; then
  mv "$OUT_DIR/hairtag.svg" "$OUT_DIR/schematic.svg"
  echo "  -> doc/schematic.svg"
fi

echo "Exporting PCB composite SVG..."
"$KICAD_CLI" pcb export svg \
  --output "$OUT_DIR/pcb.svg" \
  --layers "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts" \
  --page-size-mode 2 \
  --fit-page-to-board \
  --exclude-drawing-sheet \
  "$PCB"

# Add margin (5mm on each side) by expanding the viewBox
# SVG units are mm in KiCad exports
MARGIN=5
VIEWBOX_LINE=$(grep -o 'viewBox="[^"]*"' "$OUT_DIR/pcb.svg")
VX=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\1/')
VY=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\2/')
VW=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\3/')
VH=$(echo "$VIEWBOX_LINE" | sed 's/viewBox="\([^ ]*\) \([^ ]*\) \([^ ]*\) \([^"]*\)"/\4/')
NEW_VX=$(echo "$VX - $MARGIN" | bc)
NEW_VY=$(echo "$VY - $MARGIN" | bc)
NEW_VW=$(echo "$VW + 2 * $MARGIN" | bc)
NEW_VH=$(echo "$VH + 2 * $MARGIN" | bc)
sed -i '' "s/viewBox=\"[^\"]*\"/viewBox=\"$NEW_VX $NEW_VY $NEW_VW $NEW_VH\"/" "$OUT_DIR/pcb.svg"

# Make copper layers semi-transparent so both sides are visible
sed -i '' 's/fill:#4D7FC4; fill-opacity:1.0000/fill:#4D7FC4; fill-opacity:0.6/g' "$OUT_DIR/pcb.svg"
sed -i '' 's/fill:#C83434; fill-opacity:1.0000/fill:#C83434; fill-opacity:0.6/g' "$OUT_DIR/pcb.svg"

# Reorder SVG groups so back layers (B.Silkscreen) render behind front layers (F.Cu, F.Silkscreen)
# KiCad exports B.Silkscreen after F layers, causing it to paint on top
python3 - "$OUT_DIR/pcb.svg" <<'PYEOF'
import sys, re

path = sys.argv[1]
with open(path, 'r') as f:
    content = f.read()

# Split into: header, top-level <g> groups, footer
# Top-level groups are direct children of <svg>
header_match = re.search(r'^(.*?<svg[^>]*>)', content, re.DOTALL)
footer_match = re.search(r'(</svg>\s*)$', content)

if not header_match or not footer_match:
    sys.exit(0)

header = header_match.group(1)
footer = footer_match.group(1)
body = content[header_match.end():footer_match.start()]

# Extract top-level <g> groups (only depth-1 groups)
groups = []
depth = 0
current = []
for line in body.split('\n'):
    stripped = line.strip()
    depth += stripped.count('<g ') - stripped.count('</g>')
    # Don't count self-closing or nested g's at wrong depth
    current.append(line)
    if depth == 0 and current:
        groups.append('\n'.join(current))
        current = []

# Classify groups by layer color
B_SILK_COLOR = '#E8B2A7'
F_CU_COLOR = '#4D7FC4'

def is_b_silkscreen(g):
    return B_SILK_COLOR in g

def is_f_cu(g):
    return F_CU_COLOR in g and 'fill' in g.split('\n')[0]

b_silk_groups = [g for g in groups if is_b_silkscreen(g)]
other_groups = [g for g in groups if not is_b_silkscreen(g)]

# Find the index of the first F.Cu group in other_groups
f_cu_idx = None
for i, g in enumerate(other_groups):
    if is_f_cu(g):
        f_cu_idx = i
        break

# Insert B.Silkscreen groups just before F.Cu
if f_cu_idx is not None and b_silk_groups:
    reordered = other_groups[:f_cu_idx] + b_silk_groups + other_groups[f_cu_idx:]
else:
    reordered = other_groups + b_silk_groups

with open(path, 'w') as f:
    f.write(header + '\n'.join(reordered) + footer)

print(f"  Reordered {len(b_silk_groups)} B.Silkscreen group(s) before F.Cu")
PYEOF

# Add dark background
sed -i '' "/<desc>Image generated by PCBNEW <\/desc>/a\\
<!-- Background rectangle -->\\
<rect x=\"$NEW_VX\" y=\"$NEW_VY\" width=\"$NEW_VW\" height=\"$NEW_VH\" fill=\"#001124\"/>
" "$OUT_DIR/pcb.svg"
echo "  -> doc/pcb.svg"

echo "Rendering PCB 3D top view..."
"$KICAD_CLI" pcb render \
  --side top \
  --quality high \
  --width 2000 \
  --height 2000 \
  -o "$OUT_DIR/pcb_3d_top.png" \
  "$PCB"
echo "  -> doc/pcb_3d_top.png"

echo "Done! Exported to doc/"
